title: Stackbit Event Theme
baseurl: /
permalink: '/:title/'
layout_type: full-width
style: classic
palette: red
mode: light
base_font: sans-serif
header:
  type: header
  template: header
  title: Event
  logo: images/logo.svg
  logo_alt: Event logo
  has_primary_nav: false
  has_secondary_nav: true
  secondary_nav_links:
    - type: action
      template: action
      label: About
      url: /about
      style: link
    - type: action
      template: action
      label: Sponsorship
      url: /sponsorship
      style: link
    - type: action
      template: action
      label: Tickets
      url: thank-you
      style: primary
  has_anncmnt: false
footer:
  type: footer
  template: footer
  has_primary_nav: false
  has_secondary_nav: false
  has_tertiary_nav: false
  has_social: false
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=event&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: '/posts/:title/'
domain: 'https://square-velociraptor-0fc10.netlify.app'
